import { Application, Container, Sprite } from "pixi.js";
import { Modpack } from "./Modding/Modpack";
import Zone from "./Graphical/Zone";
import { DebugDrawer } from "./Patching/DebugDrawer";
import { InterstellarSettings } from "./Settings";
import { ModpackManager } from "./Modding/ModpackManager";
import { TexturePack } from "./Modding/TexturePack";
import { InterstellarPacketAPI, InterstellarDrednotSettingsAPI } from "./API/StellarAPI";
import DebugMenu from "./DebugMenu";
import InterstellarScriptingMod from "./API/InterstellarScriptingMod";
import UIEventDispatcher from "./Patching/UIEventDispatcher";
interface Graphics {
    game: Container;
    background: Container;
    drednot_sprite: Sprite;
}
type Modpacks = Modpack | TexturePack;
declare class Interstellar {
    application: Application;
    drednotCanvas: HTMLCanvasElement;
    graphics: Graphics;
    patcher: {
        webgl: WebGLRenderingContext | undefined;
        wasmInstance: WebAssembly.Instance | undefined;
        audioOverrides: Record<string, string>;
        imageOverrides: Record<string, string>;
        zoom: number;
        navDestination: number;
        playerX: number;
        playerY: number;
        shipX: number;
        shipY: number;
        internalModFileManager: any;
        promptManager: any;
        inputManager: any;
        preact: any;
        msgpack: any;
        worldManager: any;
        accountManager: any;
        socketmsgtypes: any;
        htmluifunctions: any;
        textformatter: any;
        usersettingsmanager: any;
        gameActive: boolean;
        enableGriefMessages: boolean;
        loadRequires(): void;
        setWebgl(gl: WebGLRenderingContext): WebGLRenderingContext;
        setWasmInstance(instance: WebAssembly.Instance): void;
        getNavDestination(): number;
        toggleUIPatch(model: string, current: any): any;
        trigger_frame_start(): void;
        trigger_frame_end(cl: any): void;
        patchAssetTables(images: Record<string, string>, audio: Record<string, string>): void;
        handleMessage(message: any): any;
        socketclose(event: any): void;
        processMOTD(motd: string): string;
        socketopen(websocket: WebSocket): void;
        joinShip(server: number | null, data: any): Promise<void>;
        onJoinShip(server: number | null, data: any): boolean;
        patchNavNames(zone: number): string;
        onChatClose(): void;
        onSendChat(message: string): string;
        patchZoneDescription(zone: string): (string | number)[];
        drawZoneText(overworld: any, graphics: any, x: number): void;
        patchDebug(): void;
    };
    settingsManager: InterstellarSettings;
    api: {
        websocket: WebSocket | undefined;
        UI: {
            settingModels: Record<string, import("preact").VNode>;
            showPrompt(title: string, description: string, callback: Function): void;
            openPromptEx(title: string, msg: string, type: any, callback: Function, fail_callback: Function): void;
            openPromptConfirm(title: string, description: string, callback: Function): void;
            openModal(model: import("preact").VNode, error?: boolean, unclosable?: boolean): void;
            closeModel(): void;
            registerSettingsModel(name: string, model: import("preact").VNode): void;
            preactAppendChild(parent: import("preact").VNode, node: import("preact").VNode): void;
            preactInsertBefore(parent: import("preact").VNode, referenceNode: import("preact").VNode, node: import("preact").VNode): void;
            preactInsertAfter(parent: import("preact").VNode, referenceNode: import("preact").VNode, node: import("preact").VNode): void;
            preactPrependChild(parent: import("preact").VNode, node: import("preact").VNode): void;
            preactGetChildWithID(vnode: import("preact").VNode, id: string): import("preact").VNode | null;
            preactNormalizeChildren(children: any): import("preact").VNode[];
            toggleUI(model?: string): void;
            openChat(): void;
            closeChat(): void;
            writeChat(innerHTML: string): void;
            getChatInputElement(): HTMLInputElement;
            isChatInputFocused(): boolean;
        };
        Input: {
            keyDown(keyCode: string): boolean;
            keyPressed(keyCode: string): boolean;
            keyPressedFrame(keyCode: string): boolean;
            mouseX(): number;
            mouseY(): number;
            mouseButtonDown(mouseButton: number): boolean;
            mouseButtonPressed(mouseButton: number): boolean;
            mouseButtonPressedFrame(mouseButton: number): boolean;
            mouseButtonReleasedFrame(mouseButton: number): any;
            dragInventoryItem(sourceSlot: number, targetSlot: number, split?: boolean): void;
            getInputObject(): any;
            getInternalInputObject(): any;
        };
        Game: {
            sentCrewControlRequest: boolean;
            cachedCrewControl: import("./API/Utils").PlayerListEntry[];
            cachedPlayers: Set<string>;
            getLocalWorld(): any;
            getLocalOnlinePlayerNames(): string[];
            leaveShip(): any;
        };
        DrednotSettings: InterstellarDrednotSettingsAPI;
        Packet: InterstellarPacketAPI;
        currentShip: import("./API/Utils").CurrentShipData | null;
        joinShip(server: number | null, data: any): Promise<void>;
        sendPacket(packet: any): void;
        isCaptain(): boolean;
        playerName(): string;
        getSelectedServer(): number;
    };
    uiEventDispatcher: UIEventDispatcher;
    debugDrawer: DebugDrawer;
    displayBGName: string;
    assetManager: {
        database: IDBDatabase | undefined;
        internal: import("./StellarAssetManager").AssetStoreData | undefined;
        urlTable: Record<string, string>;
        modAssetTable: Record<string, import("./StellarAssetManager").AssetStoreData>;
        init(): Promise<void>;
        getUpdates(): Promise<number[]>;
        pushAssetStore(name: string, storeData: import("./StellarAssetManager").AssetStoreData): Promise<void>;
        loadAssetStore(name: string): Promise<import("./StellarAssetManager").AssetStoreData>;
        putIntoStore(store: IDBObjectStore, key: string, value: any): Promise<unknown>;
        removeFromStore(store: IDBObjectStore, key: string): Promise<unknown>;
        initDatabase(): Promise<IDBDatabase>;
        createAssetStore(name: string, dbName?: string): Promise<void>;
        deleteAssetStore(name: string, dbName?: string): Promise<void>;
        reloadDatabaseWithUpgrade(dbName: string, upgrade: (db: IDBDatabase) => void): Promise<void>;
    };
    modpackManager: ModpackManager;
    zoneOverrides: Record<string, Zone>;
    moddedNameZones: Record<string, Zone>;
    menuZones: string[];
    loadedModpacks: Modpacks[];
    canonicalZone: string;
    font: FontFace | undefined;
    appStartPromise: Promise<void>;
    started: boolean;
    fullyLoaded: boolean;
    currentZone: Zone | null;
    lastCanvasWidth: number;
    lastCanvasHeight: number;
    debugMenu: DebugMenu;
    isFirefox: boolean;
    scriptingMods: Record<string, InterstellarScriptingMod>;
    url: string;
    isTestDred: boolean;
    connectServer: number;
    ingame: boolean;
    dev: boolean;
    constructor();
    init(): void;
    loaded(): Promise<void>;
    backgroundLoader(): Promise<void>;
    endTick(): void;
    teleport(name: string): void;
    static log(...args: any[]): void;
    static yield(): Promise<void>;
    yield(): Promise<void>;
    sendChatLog(message: string): void;
    tryImport(e: any): boolean;
}
declare const _default: Interstellar;
export default _default;
