import { MusicCache } from "./MusicPlayer";
import { InterstellarLoadingScreen } from "../InterstellarLoadingScreen";
export declare class Music {
    active: boolean;
    gainNode: GainNode;
    private _volume;
    focusVolume: number;
    fadeVolume: number;
    nextOutputAt: number;
    nextNextOutputAt: number;
    currentOutput: AudioBufferSourceNode | undefined;
    bufferNext: AudioBufferSourceNode | undefined;
    activating: boolean;
    currentTime: number;
    private _pauseTime;
    private _startPlayingTime;
    private _startPlayingOffset;
    private _musicLength;
    lastLoadedBuffer: number;
    get currentIndex(): number;
    bufferStartTime: number;
    playing: boolean;
    name: string;
    assetStore: string;
    path: string;
    hash: string;
    manifest: MusicCache | undefined;
    ticker: number;
    lastChunkLoadTime: number;
    getTickLock(): boolean;
    constructor(path: string, hash: string, startTime: number);
    load(loading: InterstellarLoadingScreen): Promise<void>;
    activate(): Promise<void>;
    tryPlay(): void;
    play(): Promise<void>;
    loadNext(): Promise<void>;
    loadBuffer(index: number): Promise<{
        source: AudioBufferSourceNode;
        length: number;
    }>;
    private _tickLock;
    stopTime: number;
    tick(dt: number, focused: boolean, volumeSetting: number): Promise<void>;
    calculateCurrentTime(): void;
    deactivate(): void;
    stop(): void;
    set volume(value: number);
    calculateGainVolume(): void;
    get volume(): number;
}
