import { VNode } from "preact";
import { CurrentShipData, PlayerListEntry } from "./Utils";
declare class InterstellarUIAPI {
    settingModels: Record<string, VNode>;
    showPrompt(title: string, description: string, callback: Function): void;
    openPromptEx(title: string, msg: string, type: any, callback: Function, fail_callback: Function): void;
    openPromptConfirm(title: string, description: string, callback: Function): void;
    openModal(model: VNode, error?: boolean, unclosable?: boolean): void;
    closeModel(): void;
    registerSettingsModel(name: string, model: VNode): void;
    preactAppendChild(parent: VNode, node: VNode): void;
    preactInsertBefore(parent: VNode, referenceNode: VNode, node: VNode): void;
    preactInsertAfter(parent: VNode, referenceNode: VNode, node: VNode): void;
    preactPrependChild(parent: VNode, node: VNode): void;
    preactGetChildWithID(vnode: VNode, id: string): VNode | null;
    preactNormalizeChildren(children: any): VNode[];
    toggleUI(model?: string): void;
    openChat(): void;
    closeChat(): void;
    writeChat(innerHTML: string): void;
    getChatInputElement(): HTMLInputElement;
    isChatInputFocused(): boolean;
    screenRender(callback: CallableFunction): void;
    drawRect(x: number, y: number, width: number, height: number, color: number): void;
    translate(x: number, y: number, callback: CallableFunction): any;
    drawRectRaw(color: number, width: number, height: number): any;
}
declare class InterstellarInputAPI {
    keyDown(keyCode: string): boolean;
    keyPressed(keyCode: string): boolean;
    keyPressedFrame(keyCode: string): boolean;
    mouseX(): number;
    mouseY(): number;
    mouseButtonDown(mouseButton: number): boolean;
    mouseButtonPressed(mouseButton: number): boolean;
    mouseButtonPressedFrame(mouseButton: number): boolean;
    mouseButtonReleasedFrame(mouseButton: number): any;
    dragInventoryItem(sourceSlot: number, targetSlot: number, split?: boolean): void;
    getInputObject(): any;
    getInternalInputObject(): any;
}
export declare class InterstellarPacketAPI {
    ClMsgCtrlCmd: any;
    ClMsgHeartbeat: any;
    ClMsgChat: any;
    ClMsgComms: any;
    ClMsgTeamAct: any;
    ClMsgPUICommand: any;
    ClMsgBlockSettings: any;
    ClMsgOutfitRequest: any;
    ClMsgEntConfig: any;
    ClMsgBlueprint: any;
    ClMsgPvPTeam: any;
    ClMsgMuteWarning: any;
    SvMsgSetPaintColor: any;
    SvMsgCommsBubble: any;
    SvMsgOutfitResponse: any;
    SvMsgItemManifest: any;
    SvMsgLabScores: any;
    SvMsgLockdownOverrideWarning: any;
    SvMsgRelayStats: any;
    SvMsgFileDownload: any;
    SvMsgSnapshot: any;
    SvMsgCamFocus: any;
    SvMsgWorldInfo: any;
    SvMsgWorldBlocks: any;
    SvMsgChat: any;
    SvMsgCaptainInfo: any;
    SvMsgMotd: any;
    SvMsgPressureInfo: any;
    ClMsgSpawnPlayer: any;
    ClMsgEndSession: any;
    ClMsgShipControl: any;
    ClMsgGetAnchor: any;
    ClMsgUpdateAnchor: any;
    ClMsgSubSpawnDrop: any;
    ClMsgShipDestruct: any;
    ClMsgShipDecay: any;
    ClMsgToggleSlew: any;
    ClMsgPickupRequest: any;
    ClMsgCombatRating: any;
    ClMsgThrustInfo: any;
    ClMsgRequestRelocate: any;
    SvMsgCtrlXfer: any;
    SvMsgKillSession: any;
    SvMsgResetShip: any;
    SvMsgKillConnection: any;
    SvMsgComms: any;
    SvMsgPickupAvailable: any;
    SvMsgPickupUnavailable: any;
    SvMsgPickupSend: any;
    SvMsgDocked: any;
    SvMsgEventWon: any;
    SvMsgEnableEliminationCrit: any;
    SvMsgProfileRelay: any;
    SvMsgPvPTeamLog: any;
    SvMsgHarmShields: any;
    ShMsgSubSpawnShot: any;
    ShMsgResizeShip: any;
    ShMsgInternalRPC: any;
}
declare class InterstellarGameAPI {
    sentCrewControlRequest: boolean;
    cachedCrewControl: PlayerListEntry[];
    cachedPlayers: Set<string>;
    getLocalWorld(): any;
    getLocalOnlinePlayerNames(): string[];
    getCameraWorldX(): any;
    getCameraWorldY(): any;
    getPlayerX(): any;
    getPlayerY(): any;
    getNavDestination(): any;
    getCurrentZone(): string;
    leaveShip(): any;
    getZoom(): number;
    getColor(x: number, y: number): number;
    setColor(x: number, y: number, color: number): void;
    drawText(text: string, x: number, y: number, color: number | string, size: number | undefined): any;
    getLatestPredictedCommandNumber(): any;
}
declare class TurretModes {
    ContinuousFire: any;
    VolleyFire: any;
}
export declare class InterstellarDrednotSettingsAPI {
    TurretModes: TurretModes;
    getSettings(): any;
    setEnableGriefingWarning(enabled: boolean): void;
}
declare class InterstellarTelemetryAPI {
    getEventSchema(): Record<string, string>;
    getEventState(): Record<string, {
        time: number;
        event: string;
    }>;
    isDisabled(): boolean;
    connected(): boolean;
}
declare class StellarAPI {
    websocket: WebSocket | undefined;
    UI: InterstellarUIAPI;
    Input: InterstellarInputAPI;
    Game: InterstellarGameAPI;
    Telemetry: InterstellarTelemetryAPI;
    Interstellar: {
        drednotCanvas: HTMLCanvasElement;
        patcher: {
            webgl: WebGL2RenderingContext | undefined;
            audioOverrides: Record<string, string>;
            imageOverrides: Record<string, string>;
            zoom: number;
            navDestination: number;
            playerX: number;
            playerY: number;
            shipX: number;
            shipY: number;
            internalModFileManager: any;
            promptManager: any;
            inputManager: any;
            preact: any;
            msgpack: any;
            worldManager: any;
            accountManager: any;
            socketmsgtypes: any;
            htmluifunctions: any;
            textformatter: any;
            graphics: any;
            usersettingsmanager: any;
            gameActive: boolean;
            enableGriefMessages: boolean;
            sendChatCallback: any;
            interstellarInternals: any;
            resolveWaitRequires: any;
            waitRequires: Promise<void>;
            resolveWebGL: any;
            waitWebGL: Promise<void>;
            loadRequires(): void;
            setWebgl(_gl: WebGL2RenderingContext): WebGL2RenderingContext;
            getNavDestination(): any;
            toggleUIPatch(model: string, current: any): any;
            trigger_frame_start(): void;
            trigger_frame_end(cl: any): void;
            finalize_frame(): void;
            patchAssetTables(images: Record<string, string>, audio: Record<string, string>): void;
            handleMessage(message: any): any;
            handleMessageSend(message: any): any;
            socketclose(event: any): void;
            processMOTD(motd: string): string;
            socketopen(websocket: WebSocket): void;
            joinShip(server: number | null, data: any): Promise<void>;
            onJoinShip(server: number | null, data: any): boolean;
            getPlayerPosition(): {
                x: any;
                y: any;
            };
            patchNavNames(zone: number): string;
            onChatClose(): void;
            onSendChat(message: string): string;
            patchZoneDescription(zone: string): (string | number)[];
            drawZoneText(overworld: any, graphics: any, x: number): void;
            patchDebug(): void;
            renderAdverts(): boolean;
            processAdverts(data: any): void;
            clickAdverts(url: string, hover_sign: any): string | null;
            drawOnTop(): void;
            rp1(world: any): boolean;
            rp2(world: any): boolean;
            rp3(world: any): boolean;
            postprocess(): void;
            startBorderRender(): void;
            endBorderRender(): void;
            update_ship_info(health: number, max_health: number, warp_time: number, max_warp_time: number, overworld: any, ship_world: any): void;
            doShipyardFilters(props: any): boolean;
        };
        settingsManager: import("../Settings").InterstellarSettings;
        api: StellarAPI;
        uiEventDispatcher: import("../Patching/UIEventDispatcher").default;
        debugDrawer: import("../Patching/DebugDrawer").DebugDrawer;
        displayBGName: string;
        assetManager: {
            database: IDBDatabase | undefined;
            internal: import("../StellarAssetManager").AssetStoreData | undefined;
            urlTable: Record<string, string>;
            modAssetTable: Record<string, import("../StellarAssetManager").AssetStoreData>;
            internalMap: Record<string, string>;
            assetPaths: string[];
            reference_counter: number;
            init(): Promise<void>;
            getUpdates(): Promise<number[]>;
            getInternalUpdates(): [string[], string[]];
            pushAssetStore(name: string, storeData: import("../StellarAssetManager").AssetStoreData): Promise<void>;
            loadAssetStore(name: string): Promise<import("../StellarAssetManager").AssetStoreData>;
            putIntoStore(store: IDBObjectStore, key: string, value: any): Promise<unknown>;
            removeFromStore(store: IDBObjectStore, key: string): Promise<unknown>;
            initDatabase(): Promise<IDBDatabase>;
            openDatabase(): Promise<IDBDatabase>;
            closeDatabase(): Promise<void>;
            createAssetStore(name: string, dbName?: string): Promise<void>;
            deleteAssetStore(name: string, dbName?: string): Promise<void>;
            reloadDatabaseWithUpgrade(dbName: string, upgrade: (db: IDBDatabase) => void): Promise<void>;
        };
        modpackManager: import("../Modding/ModpackManager").ModpackManager;
        zoneOverrides: Record<string, import("../Graphical/Zone").default>;
        moddedNameZones: Record<string, import("../Graphical/Zone").default>;
        menuZones: string[];
        loadedModpacks: (import("../Modding/Modpack").Modpack | import("../Modding/TexturePack").TexturePack)[];
        canonicalZone: string;
        font: FontFace | undefined;
        started: boolean;
        fullyLoaded: boolean;
        currentZone: import("../Graphical/Zone").default | null;
        debugMenu: import("../DebugMenu").default;
        isFirefox: boolean;
        scriptingMods: Record<string, import("./InterstellarScriptingMod").default>;
        url: string;
        isTestDred: boolean;
        connectServer: number;
        ingame: boolean;
        dev: boolean;
        failedLoading: [string, string, any][];
        build: number;
        telemetry: import("../Telemetry").default;
        badge_url: string;
        lastDelta: number;
        deltaTime: number;
        init(): void;
        modsAreConfigurable: boolean;
        loaded(): Promise<void>;
        backgroundLoader(): Promise<void>;
        startTick(): void;
        endTick(): void;
        teleport(name: string): void;
        reload_zone(): void;
        yield(): Promise<void>;
        sendChatLog(message: string): void;
        tryImport(e: any): boolean;
        finalize_frame(): void;
        reportFailed(modid: string, message: string, error: any): void;
        getBadgeURL(): string;
    };
    DrednotSettings: InterstellarDrednotSettingsAPI;
    Packet: InterstellarPacketAPI;
    currentShip: CurrentShipData | null;
    joinShip(server: number | null, data: any): Promise<void>;
    sendChat(text: string, no_events: boolean | undefined): void;
    sendPacket(packet: any): void;
    isCaptain(): boolean;
    playerName(): string;
    getSelectedServer(): number;
}
declare const _default: StellarAPI;
export default _default;
