declare class Patcher {
    webgl: WebGL2RenderingContext | undefined;
    audioOverrides: Record<string, string>;
    imageOverrides: Record<string, string>;
    zoom: number;
    navDestination: number;
    playerX: number;
    playerY: number;
    shipX: number;
    shipY: number;
    internalModFileManager: any;
    promptManager: any;
    inputManager: any;
    preact: any;
    msgpack: any;
    worldManager: any;
    accountManager: any;
    socketmsgtypes: any;
    htmluifunctions: any;
    textformatter: any;
    graphics: any;
    usersettingsmanager: any;
    gameActive: boolean;
    enableGriefMessages: boolean;
    sendChatCallback: any;
    interstellarInternals: any;
    resolveWaitRequires: any;
    waitRequires: Promise<void>;
    resolveWebGL: any;
    waitWebGL: Promise<void>;
    constructor();
    loadRequires(): void;
    setWebgl(_gl: WebGL2RenderingContext): WebGL2RenderingContext;
    getNavDestination(): any;
    toggleUIPatch(model: string, current: any): any;
    trigger_frame_start(): void;
    trigger_frame_end(cl: any): void;
    finalize_frame(): void;
    patchAssetTables(images: Record<string, string>, audio: Record<string, string>): void;
    handleMessage(message: any): any;
    handleMessageSend(message: any): any;
    socketclose(event: any): void;
    processMOTD(motd: string): string;
    socketopen(websocket: WebSocket): void;
    joinShip(server: number | null, data: any): Promise<void>;
    onJoinShip(server: number | null, data: any): boolean;
    getPlayerPosition(): {
        x: any;
        y: any;
    };
    patchNavNames(zone: number): string;
    onChatClose(): void;
    onSendChat(message: string): string;
    patchZoneDescription(zone: string): (string | number)[];
    drawZoneText(overworld: any, graphics: any, x: number): void;
    patchDebug(): void;
    renderAdverts(): boolean;
    processAdverts(data: any): void;
    clickAdverts(url: string, hover_sign: any): string | null;
    drawOnTop(): void;
    rp1(world: any): boolean;
    rp2(world: any): boolean;
    rp3(world: any): boolean;
    postprocess(): void;
    startBorderRender(): void;
    endBorderRender(): void;
    update_ship_info(health: number, max_health: number, warp_time: number, max_warp_time: number, overworld: any, ship_world: any): void;
}
declare const _default: Patcher;
export default _default;
