declare class Patcher {
    webgl: WebGLRenderingContext | undefined;
    wasmInstance: WebAssembly.Instance | undefined;
    audioOverrides: Record<string, string>;
    imageOverrides: Record<string, string>;
    zoom: number;
    navDestination: number;
    playerX: number;
    playerY: number;
    shipX: number;
    shipY: number;
    internalModFileManager: any;
    promptManager: any;
    inputManager: any;
    preact: any;
    msgpack: any;
    worldManager: any;
    accountManager: any;
    socketmsgtypes: any;
    htmluifunctions: any;
    textformatter: any;
    usersettingsmanager: any;
    gameActive: boolean;
    enableGriefMessages: boolean;
    constructor();
    loadRequires(): void;
    setWebgl(gl: WebGLRenderingContext): WebGLRenderingContext;
    setWasmInstance(instance: WebAssembly.Instance): void;
    getNavDestination(): number;
    toggleUIPatch(model: string, current: any): any;
    trigger_frame_start(): void;
    trigger_frame_end(cl: any): void;
    patchAssetTables(images: Record<string, string>, audio: Record<string, string>): void;
    handleMessage(message: any): any;
    socketclose(event: any): void;
    processMOTD(motd: string): string;
    socketopen(websocket: WebSocket): void;
    joinShip(server: number | null, data: any): Promise<void>;
    onJoinShip(server: number | null, data: any): boolean;
    patchNavNames(zone: number): string;
    onChatClose(): void;
    onSendChat(message: string): string;
    patchZoneDescription(zone: string): (string | number)[];
    drawZoneText(overworld: any, graphics: any, x: number): void;
    patchDebug(): void;
}
declare const _default: Patcher;
export default _default;
